# Python Numpy Arrays

In [1]:
import numpy as np

In [3]:
lst = [1,2,3,4,4]
arr = np.array(lst)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(5,)

In [8]:
lst1 = [1,2,3,4,5]
lst2 = [2,3,4,5,6]
lst3 = [3,4,5,6,7]
arr1 = np.array([lst1,lst2,lst3])

In [9]:
arr1.shape

(3, 5)

In [10]:
arr

array([1, 2, 3, 4, 4])

In [11]:
#indexing

In [12]:
arr[3]

4

In [13]:
arr[4] = 5 

In [14]:
arr


array([1, 2, 3, 4, 5])

In [16]:
arr[1:]

array([2, 3, 4, 5])

In [17]:
arr[:-1]

array([1, 2, 3, 4])

In [18]:
arr[::-1]

array([5, 4, 3, 2, 1])

In [19]:
arr[::-2]

array([5, 3, 1])

In [20]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [21]:
arr1[:,1]

array([2, 3, 4])

In [24]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [25]:
arr1[1:,2:]

array([[4, 5, 6],
       [5, 6, 7]])

In [26]:
arr1[2:,2:]

array([[5, 6, 7]])

In [27]:
arr1[:,3:]

array([[4, 5],
       [5, 6],
       [6, 7]])

In [29]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [32]:
arr1[:,::4]

array([[1, 5],
       [2, 6],
       [3, 7]])

In [33]:
#EDA
arr

array([1, 2, 3, 4, 5])

In [36]:
arr[arr<2]

array([1])

In [37]:
arr1.shape

(3, 5)

In [43]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [46]:
#mechanism to create an array
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [48]:
arr


array([1, 2, 3, 4, 5])

In [47]:
arr*arr

array([ 1,  4,  9, 16, 25])

In [49]:
arr*2

array([ 2,  4,  6,  8, 10])

In [50]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
np.random.randint(10,50,4).reshape(2,2)

array([[21, 15],
       [23, 38]])

In [66]:
np.random.randn(5,6)

array([[-1.17546451,  0.10842172,  0.03920239,  0.27935993, -1.93059656,
        -0.7647854 ],
       [ 1.35544679, -0.30611312, -1.38274527,  1.40411496, -1.1493021 ,
        -1.26740188],
       [-0.24756212, -1.3197537 ,  0.98566571, -0.13337046, -0.70883215,
         1.07470491],
       [-0.88047627,  1.1251409 ,  0.12893585,  0.67257037,  0.59634774,
         0.66959996],
       [-1.7624103 , -0.03263931,  0.38120443, -1.39277207, -1.65188294,
        -0.82386001]])